### ISSUE TITLE
Preferred versions on Hackage

### ISSUE THREAD

**Issue by lehins** [Lokidottir/typerbole#11]
Not sure if it was intentional, but currently on hackage preferred versions are set to `typerbole >=1.0.0.0`, while current version is `0.0.0.5`. 
Here is the reference: http://hackage.haskell.org/packages/preferred-versions

**Comment by Lokidottir** [comment]
This was intentional, what's available on hackage doesn't have working unification - when that's fixed I'll publish a 1.0.0.0 to hackage.

**Comment by lehins** [comment]
That's cool. But just to let you know that it doesn't make sense to not have at least one preferred version on Hackage:
> If all the available versions of a package are non-preferred or deprecated, cabal-install will treat this the same as if none of them are.

**Comment by Lokidottir** [comment]
I wasn't aware of this, I'll work on this enough to get a 1.0 up ASAP.
